from typing import Protocol

from backend.app.domain.models import SourceRecord


class SourceRepository(Protocol):
    def create(self, source: SourceRecord) -> None: ...

    def update(self, source: SourceRecord) -> None: ...

    def get(self, source_id: str) -> SourceRecord | None: ...

    def list(self, *, limit: int, offset: int) -> list[SourceRecord]: ...

    def count(self) -> int: ...

    def delete(self, source_id: str) -> None: ...
