from __future__ import annotations

from typing import Protocol

from backend.app.domain.tabular_models import TabularRunRecord


class TabularRunRepository(Protocol):
    def create(self, run: TabularRunRecord) -> TabularRunRecord: ...

    def update(self, run: TabularRunRecord) -> TabularRunRecord: ...

    def get(self, run_id: str) -> TabularRunRecord | None: ...

    def get_by_idempotency_key(self, key: str) -> TabularRunRecord | None: ...

    def list(self, *, limit: int, offset: int) -> list[TabularRunRecord]: ...

    def count(self) -> int: ...

    def list_job_ids_for_source(self, source_id: str) -> list[str]: ...
